export const programaContent = {
    header: ['Hora', 'Actividades Virtuales', 'Actividades presenciales'],
    sabado: [
        { hora: '09:30', virtual: 'Bienvenida al evento', presencial: '' },
        { hora: '10:00', virtual: 'Rebeca Anaya', presencial: '' },
        { hora: '10:30', virtual: 'Rodrigo', presencial: '' },
        { hora: '11:00', virtual: 'Jess', presencial: '' },
        { hora: '11:30', virtual: '', presencial: '' },
        {
            hora: '12:00',
            virtual: 'Así no se hace con Fer Cozzi',
            presencial: '',
        },
        {
            hora: '12:30',
            virtual: 'Así no se hace con Fer Cozzi',
            presencial: '',
        },
        {
            hora: '13:00',
            virtual: 'Así no se hace con Fer Cozzi',
            presencial: '',
        },
        {
            hora: '13:30',
            virtual: 'Así no se hace con Fer Cozzi',
            presencial: '',
        },
        {
            hora: '14:00',
            virtual: 'Así no se hace con Fer Cozzi',
            presencial: '',
        },
        {
            hora: '14:30',
            virtual: 'Así no se hace con Fer Cozzi',
            presencial: '',
        },
        { hora: '15:00', virtual: '', presencial: '' },
        { hora: '15:30', virtual: '', presencial: '' },
        { hora: '16:00', virtual: 'David', presencial: '' },
        { hora: '16:30', virtual: '', presencial: '' },
        {
            hora: '17:00',
            virtual: '',
            presencial: 'Inauguración de anti exposición',
        },
    ],
    domingo: [
        {
            hora: '10:00',
            virtual: 'Mesa redonda',
            presencial: 'Destruyendo una fuente con Python',
        },
        {
            hora: '10:30',
            virtual: 'Mesa redonda',
            presencial: 'Destruyendo una fuente con Python',
        },
        {
            hora: '11:00',
            virtual: 'Mesa redonda',
            presencial: 'Destruyendo una fuente con Python',
        },
        {
            hora: '11:30',
            virtual: 'Mesa redonda',
            presencial: 'Destruyendo una fuente con Python',
        },
        {
            hora: '12:00',
            virtual: '',
            presencial: 'Destruyendo una fuente con Python',
        },
        {
            hora: '12:30',
            virtual: '',
            presencial: 'Destruyendo una fuente con Python',
        },
        { hora: '13:00', virtual: '', presencial: '' },
        { hora: '13:30', virtual: '', presencial: '' },
        { hora: '14:00', virtual: '', presencial: '' },
        { hora: '14:30', virtual: '', presencial: 'Erika' },
        { hora: '15:00', virtual: '', presencial: 'Chris' },
        { hora: '15:30', virtual: '', presencial: '' },
        { hora: '16:00', virtual: '', presencial: 'Suck My Type' },
        { hora: '16:30', virtual: '', presencial: 'Eduardo' },
        { hora: '17:00', virtual: '', presencial: 'Alme' },
        { hora: '17:30', virtual: '', presencial: 'Mara' },
        { hora: '18:00', virtual: '', presencial: '' },
        { hora: '18:30', virtual: '', presencial: 'Mesa redonda' },
        { hora: '19:00', virtual: '', presencial: 'Mesa redonda' },
        { hora: '19:30', virtual: '', presencial: 'Mesa redonda' },
        { hora: '20:00', virtual: '', presencial: 'Chelas & tipos' },
    ],
};
